### ISSUE TITLE
PINN solver benchmarks are broken

### ISSUE THREAD

**Issue by killah-t-cell** [SciML/SciMLBenchmarks.jl#353]
Parts of the PINN solver benchmarks are not compiling

<img width="1024" alt="Screenshot 2021-11-30 at 10 49 59" src="https://user-images.githubusercontent.com/26853713/144024496-45273ce1-fd93-4bc3-98de-f8b52f59e947.png">

https://benchmarks.sciml.ai/html/PINNErrorsVsTime/allen_cahn_et.html

**Comment by ChrisRackauckas** [comment]
Yes, I pinged @KirillZubov and @francescocalisto on fixing it, though if anyone wants to get to it first be my guest because I don't plan to get to it any time soon. I was just trying to get the benchmarks like 90% setup so that others can then help 😅

**Comment by KirillZubov** [comment]
look like just outdated code after update and it is just need add couple new parameter to build_loss_function.

**Comment by KirillZubov** [comment]
https://github.com/SciML/SciMLBenchmarks.jl/pull/355

I fixed allen_cahn. Not sure about the results of the prediction. 

@francescocalisto could you please check how much iteration is needed and etc.  

Also, other scripts in PINNErrorsVsTime need to update because there also use low-level API which was changed, and code outdate. 
https://github.com/SciML/SciMLBenchmarks.jl/tree/master/benchmarks/PINNErrorsVsTime

**Comment by ChrisRackauckas** [comment]
This is fixed.
