### ISSUE TITLE
Scale which benchmarking has been done?

### ISSUE THREAD

**Issue by DrVogt** [SciML/SciMLBenchmarks.jl#399]
Howdy,

I was curious if benchmarking found at https://benchmarks.sciml.ai/html/MultiLanguage/wrapper_packages.html

and in more general, here in this git repo, would hold on HPC (or is it already assumed benchmarking is done on HPC)?

**Comment by ChrisRackauckas** [comment]
This is mentioned in the README.

> Each of the benchmarks displays the computer characteristics at the bottom of the benchmark. Since performance-necessary computations are normally performed on compute clusters, the official benchmarks use a workstation with an AMD EPYC 7502 32-Core Processor @ 2.50GHz to match the performance characteristics of a standard node in a high performance computing (HPC) cluster or cloud computing setup.

That said, that script is a bit older since it can't be run on the automated benchmarking system due to the proprietary software licenses required, but that specific benchmark is much too small for that to really matter. The PDE benchmarks like https://gist.github.com/ChrisRackauckas/0bdbea0079a8a3ce28522e9bc8473bf0 would matter more for threading, since small 10 ODE systems are solved mostly in serial (other than when considering methods which only exist in OrdinaryDiffEq.jl).

**Comment by ChrisRackauckas** [comment]
We do need to extend the number of PDE scaling benchmarks, but the interesting thing would not be to test against SciPy MATLAB etc. since those packages don't have the right infrastructure to scale, so it would be an unexciting waste of tons of compute to do a sparse direct solve vs a distributed preconditioned Newton-Krylov that slaughters SciPy (which https://gist.github.com/ChrisRackauckas/0bdbea0079a8a3ce28522e9bc8473bf0 already shows). What's more interesting would be to do tests against Sundials distributed NVectors and such. That's something that would take a bit of time but would be highly worthwhile.

**Comment by DrVogt** [comment]
Hi @ChrisRackauckas  - thanks for the response, and clarification. Yes, I think tests againist LLNL's Sundials would be interesting. I also think PETsc ANL would be another great benchmark comparison (especially for solving DE, etc with their linear algebra routines). Yesterday a colleague showed me your project(s), and I am extremely impressed by the vast amount of support you have for the "big" areas of math- I feel like you have like 95% of "applied math" topics implemented, which is quite interesting.

I did notice you had random DE's as well (https://github.com/SciML/DiffEqUncertainty.jl). I was just curious if you have global sensitivity analysis (i.e sobol indices), and frequenist/bayesian UQ hideen somewhere as more data driven approaches, compared to random DE's? If not, is there plans to move towards those subjects (that seems to be that last 5% you are missing to me right now)?

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/GlobalSensitivity.jl
https://github.com/SciML/DiffEqBayes.jl, though mostly https://turing.ml/dev/tutorials/10-bayesian-differential-equations/ is the better way to do it. I'm not sure it makes sense to compare that to SDEs and RODEs though since they are modeling the noise in different ways, so it's more of a modeling assumption kind of thing. We do need more UQ methods though. https://github.com/timueh/PolyChaos.jl is worth a look.

**Comment by DrVogt** [comment]
Hi @ChrisRackauckas  - thanks for the response, and pointing me towards turing, I actually wasn't aware someone had done bayesian UQ to this level in julia. If you are interested in building the "big parts" of UQ, a good roadmap is found in Uncertainity Quantification: Theory, Implemtnation, and Application by Ralph C. Smith. Might be a good project for a Ph.D student during the summer.
